#!/usr/bin/env php
<?php
/*

  check_nems_osb - Version 1.1
  Written by Robbie Ferguson for NEMS Linux
  -----
  1.1 - May 21, 2021 - Remove the state output. Let NEMS use exit codes.
  1.0 - December 8, 2020 - Initial release

*/
  $auth=shell_exec('/usr/local/bin/nems-info cloudauth');
  if ($auth == 0) {
    // UNKNOWN State
    echo 'NEMS Cloud Services not authorized.';
    exit(3);
  }
  $osb_log = '/var/log/nems/nems-osb.log';
  if (file_exists($osb_log)) {
    $log = explode('::',shell_exec('tail -n 1 ' . $osb_log));
    if ($log[1] == 2) {
      // CRITICAL State
      echo 'OSB ' . $log[2] . ': ' . $log[3];
      exit(2);
    } else if ($log[1] == 1 && strtotime($log[0]) < strtotime('-2 days')) {
      // WARNING State
      echo 'Last OSB was ' . date('l M j, Y',strtotime($log[0]));
      exit(1);
    } else if ($log[1] == 1) {
      // OK State
      echo 'OSB ' . $log[2] . ' (' . date('l M j, Y',strtotime($log[0])) . ')';
      exit(0);
    }
  } else {
    echo 'NEMS OSB has not run.';
    exit(3);  
  }
?>
