#!/bin/bash
chown -R nagios:nagios /etc/check_wmi_plus
java -cp /usr/lib/nagios/plugins/ibmi/nagios4i.jar com.ibm.nagios.config.Initialization

# The monit config file is included in nems-scripts
# Restart in case anything changed
/bin/systemctl restart monit
