#!/bin/bash
chown -R nagios:nagios /etc/check_wmi_plus
java -cp /usr/lib/nagios/plugins/ibmi/nagios4i.jar com.ibm.nagios.config.Initialization

# The monit config file is included in nems-scripts
# Restart in case anything changed
/bin/systemctl restart monit

# check_fortigate
cpan -i Net::SNMP
cpan -i List::Compare
cpan -i Getopt::Long
cpan -i Pod::Usage
cpan -i Switch

# Python modules required by check_netscaler.py
# These are already installed on NEMS Linux
# - JSON
# - Monitoring::Plugin
